Upgrade Code Climate usage
This resolves the following message which was breaking the builds:

```
This usage of the Code Climate Test Reporter is now deprecated. Since version

1.0, we now require you to run `SimpleCov` in your test/spec helper, and then
run the provided `codeclimate-test-reporter` binary separately to report your
results to Code Climate.

More information here: https://github.com/codeclimate/ruby-test-reporter/blob/master/README.md
```

Since this reporter is deprecated, we have to upgrade to the latest version, example:
https://docs.codeclimate.com/docs/travis-ci-test-coverage

More on SimpleCov here:
https://github.com/colszowka/simplecov

I also bumped the Ruby patch-level to 2.3.6 (from 2.3.0)
and added Firefox 49 and geckodriver for the test suite.

Need to require aruba/rspec

This resolves the following error:

```
  1) Installation errors with the expected message

     Failure/Error: setup_aruba

     NameError:

       undefined local variable or method `setup_aruba' for #<RSpec::ExampleGroups::Installation:0x00000004efa4a8>

     # ./spec/spec_helper.rb:41:in `block (2 levels) in <top (required)>'
```

From this build:
https://travis-ci.org/jejacks0n/teaspoon/jobs/311055783

See aruba docs for more:
https://relishapp.com/cucumber/aruba/docs/rspec/getting-started-with-rspec-and-aruba